### ISSUE TITLE
mention worst/average case, and space usage?

### ISSUE THREAD

**Issue by adamdecaf** [yourbasic/radix#2]
Cool library. Having a drop-in for `sort.Strings` is fantastic.  (Say hi to [/r/golang](https://www.reddit.com/r/golang/comments/82davi/this_dropin_replacement_for_sortstrings_can_be/)!) 

The best case for any algorithm is, well, best, but what about the average and worst case? Those can dramatically impact the long tail (e.g. regarding timings or throughput). Could the README mention those? 

> For string sorting, a carefully implemented radix sort can be considerably faster than Quicksort, sometimes more than twice as fast.

Mentioning the space used is helpful to know, also. An `O(n)` algorithm on operations is useless if it takes `O(n!)` space!

**Comment by korthaj** [comment]
Those are good suggestions, I'll certainly add some more info. Thanks!
